name: Artemis
description: A Fantasy Microcomputer
theme: jekyll-theme-dinky
markdown: kramdown

plugins:
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
      # This might be 'close enough'
      default_lang: basic
